# Generated by Django 5.0.4 on 2024-05-10 01:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('found', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foundperson',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='foundperson',
            name='address',
            field=models.CharField(blank=True, default='egypt', max_length=50),
        ),
        migrations.AddField(
            model_name='foundperson',
            name='city',
            field=models.CharField(blank=True, default='empty', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='foundperson',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='foundperson',
            name='finder_name',
            field=models.CharField(default='ali', max_length=100),
        ),
        migrations.AddField(
            model_name='foundperson',
            name='phone_number',
            field=models.CharField(default='empty', max_length=100),
        ),
        migrations.AddField(
            model_name='foundperson',
            name='photo',
            field=models.ImageField(default='photos/%y/%m/%1', upload_to='photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='foundperson',
            name='age',
            field=models.FloatField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='foundperson',
            name='name',
            field=models.CharField(blank=True, default='empty', max_length=100),
        ),
    ]
