# Generated by Django 5.0.4 on 2024-05-10 01:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('found', '0004_alter_foundperson_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundperson',
            name='date',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
    ]
