# Generated by Django 5.0.4 on 2024-04-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lostperson',
            options={'ordering': ['name'], 'verbose_name': 'Losts'},
        ),
        migrations.AddField(
            model_name='lostperson',
            name='photo',
            field=models.ImageField(default='photos/%y/%m/%1', upload_to='photos/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='lostperson',
            name='type',
            field=models.CharField(blank=True, choices=[('lost', 'lost'), ('finded', 'finded')], default='', max_length=50),
        ),
    ]
