# Generated by Django 5.0.4 on 2024-05-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0003_alter_lostperson_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostperson',
            name='current_date_time',
        ),
        migrations.RemoveField(
            model_name='lostperson',
            name='time',
        ),
        migrations.RemoveField(
            model_name='lostperson',
            name='type',
        ),
        migrations.AddField(
            model_name='lostperson',
            name='address',
            field=models.CharField(blank=True, default='egypt', max_length=50),
        ),
        migrations.AddField(
            model_name='lostperson',
            name='city',
            field=models.CharField(blank=True, default='empty', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='lostperson',
            name='finder_name',
            field=models.CharField(default='ali', max_length=100),
        ),
        migrations.AddField(
            model_name='lostperson',
            name='phone_number',
            field=models.CharField(default='empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='lostperson',
            name='age',
            field=models.FloatField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='lostperson',
            name='name',
            field=models.CharField(blank=True, default='empty', max_length=100),
        ),
    ]
