# Generated by Django 5.0.4 on 2024-05-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0004_remove_lostperson_current_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostperson',
            name='age',
            field=models.FloatField(blank=True, default=10, null=True),
        ),
    ]
