# Generated by Django 5.0.6 on 2024-06-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0007_alter_lostperson_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostperson',
            name='name',
            field=models.CharField(blank=True, default='empty', max_length=100),
        ),
    ]
