# Generated by Django 5.0.4 on 2024-04-23 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_user_password_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
    ]
